### ISSUE TITLE
Why is my temperature NaN?

### ISSUE THREAD

**Issue by Windavilin** [wendall911/Homeostatic#40]
I'm sorry to bother you again, but when I was playing with Homeostatic 2.9.4.5, I noticed that my temperature suddenly changed to this. After that, I stayed in the 50 ℃ heat radiation for two minutes and did not see any changes in my body temperature. Why is this?
![image](https://github.com/wendall911/Homeostatic/assets/141706381/80d58f84-21f9-44c3-a624-64182e46fad2)

**Comment by wendall911** [comment]
This is for certain a bug. Does it remain after logging out and back in?

**Comment by Windavilin** [comment]
This error still exists when logging out and logging back in;After restarting the client, I was marked as a ticketing player and unable to access the server

**Comment by Windavilin** [comment]
After repeated attempts, the server can be accessed, but this error still exists
![image](https://github.com/wendall911/Homeostatic/assets/141706381/0b76a118-2053-4899-9f5c-e9629641a3ae)

**Comment by Windavilin** [comment]
I tried restarting the server, but the result was the same

**Comment by wendall911** [comment]
Ok, I will see if I can reproduce this and get a fix out soon.

**Comment by JiuyeAyan** [comment]
> Ok, I will see if I can reproduce this and get a fix out soon.

![image](https://github.com/wendall911/Homeostatic/assets/90959597/81c5abc0-dd1b-4dad-8094-62d76ce59c2f)
My temperature is NaN as well

and I have only these mods:
![image](https://github.com/wendall911/Homeostatic/assets/90959597/4dcc7271-3af7-4525-a3af-3a15bbd095df)

It happens when I create a new world.
And sometimes when I create a new world, my body temperature is 98℃
And sometimes when I create a new world, it's -17℃ on the ground, but if I dive into the water, the environment temperature is 20℃

**Comment by wendall911** [comment]
I think this has been a bug for a while. I should have a release out today for this.

**Comment by wendall911** [comment]
Ok, fixed and released for all versions. This was (sort of) a math bug. Math.pow implementation returns NaN by specification when getting a power for negative numbers, even though it is technically a valid math problem. There aren't any situations without loading Primal Winter where this can occur, so it was working correctly. It was good that adding this mod exposed a math bug. Thanks for reporting!
