### ISSUE TITLE
[Suggestion] Make thirst more reactive to player movement

### ISSUE THREAD

**Issue by Maiazye** [wendall911/Homeostatic#59]
I died due to thirst because I afked for hours and forgot to pause. It's NBD for me, but I can imagine this can be very frustrating for something like a hardcore world. In vanilla, this isn't much of an issue because hunger is only drained by player action. However, thirst is mostly passive and only increases/decreases based on ambient temperature. 

In addition to the afk issue, normal gameplay suffers from the current thirst calculation. Thirst feels too consistent compared to hunger. Hunger makes you constantly concerned with things like sprinting and taking damage, while thirst has no such effect. 

Maybe making thirst reactive to movements directly is too much to ask, considering the hunger system is rather complicated. If it is, maybe thirst can increase relative to hunger, and the magnitude of that change would be based on ambient temperature.

**Comment by Maiazye** [comment]
After reviewing the config, I now realize there is a line for "randomWaterLoss" along with a comment that implies that that the mod already has active and passive thirst mechanics. Assuming changing the "randomWaterLoss" value to 0 disables the passive drain, I guess what I should really be asking for is a config parameter to control active water loss.

**Comment by wendall911** [comment]
Water usage is consistent and behaves correctly. It does not work exactly like hunger, because that's not how the body works. With homeostatis (which the mod is designed around), water usage varies based on temperature. If it is hot, you'll sweat. If it is cold, you won't. This adjusts based on how warm it is. Go to a warm environment and go afk. I assure you, death will come from thirst long before hunger. So the reason hunger is consistent is because it doesn't have temperature related usage implications, other than when shivering when in a cold environment, then you'll use food faster because you'll be shivering.

Water usage while sprinting could happen if calculating body temperature increase. However, this would need to happen when doing pretty much anything other than standing, so for gameplay balance, we decided to not add this feature. Also, the calculations are tricky for sweating when doing activity. If it is cold, you won't sweat, if warm, you'll not sweat more, so is irrelevant. So the effect overall would not really be noticeable (yes we did test this concept, and it doesn't make any sense). What we did instead is have a random amount of water that gets used in normal circumstances (when not sweating or shivering).

This mod does what it is supposed to be doing, you'll find that it does not however work like TAN or any other temperature/thirst mods that treat temperature like magic and water like food.

I'm closing this issue as not planned. If you do any coding at all, here is the code that drives this logic: https://github.com/wendall911/Homeostatic/blob/8e99c30814caafae5129ded8c849282268c8598e/Common/src/main/java/homeostatic/common/temperature/BodyTemperature.java#L115

**Comment by wendall911** [comment]
@Maiazye Also, if you have any other questions, feel free to ask, I will be happy to clarify.

I have a bunch of stuff in the wiki on how temperature works. This reminds me I need to add a section for water usage as well: https://github.com/wendall911/Homeostatic/wiki/Temperature-Calculations

**Comment by wendall911** [comment]
@Maiazye temperature already controls active water loss.

**Comment by Maiazye** [comment]
While I disagree with some of the approaches you lay out, I at least now understand your philosophy around the system. I still insist on adding config options to affect active water loss, but I see why would wouldn't change the default thirst mechanics. 

I'm not familiar with java yet, but I'll give tweaking your mod a try. I appreciate you taking the time to give me an in depth explanation, pointing me source for the mechanic, and doing doing both promptly.

**Comment by wendall911** [comment]
This works like the human body. TAN has broken all view of how temperature and thirst work, to the point that it is frustrating. Literally read through wikipedia on how homeostatis works and you'll have a better understanding of the  mod. I'd recommend just using the other broken temperature mods as they will suit your needs better. They treat temperature and thirst like magic.

**Comment by wendall911** [comment]
I'm not deflecting here. I'm just stating that your approach to understanding is very wrong. This was not just another clone of the broken temperature implementation in TAN. Literally this was created because none of the others even attempt to create something that isn't just magic.

**Comment by Maiazye** [comment]
To be clear, I'm definitely not asking for this to be another TaN clone. I've used many temperature mods and I'm aware of the flaws you're alluding to. I think your mod is good, but it's not because it's realistic, or because it "works like the human body". I like it because feels fair and manageable. 

I was under the impressions that this mods whole premise is based on body temperature normalizing around a certain point, hence the name 'Homeostatic'. Your responses make me think that you're trying to emulate homeostasis, and that it's not just a premise to build a better temperature mod. In that emulation, the player is required to sweat simply to maintain their body temperature, which justifies the passive water drain of your mod. This is what I was referring to in regards to understanding your philosophy. 

My issue was specifically with the thirst system as it relates to player interactions. You must admit, the thirst system stands out from Minecraft's survival mechanics. Time is never used as a resource like this in the base game. Hunger is the most comparable mechanic, but time is not a factor, it's completely based on player activity. I thought that making the player activities dictate thirst would be a reasonable ask, but I see now that it conflicts with the realism aspect you're trying to achieve. That's why I conceded that changing the default state of the mod would be unreasonable, and instead asked if you could add the aforementioned config options for players that want to tweak their experience. 

I hope I didn't say anything that you feel denigrates your work. While non of your responses have been outright hostile, I do get the sense that you don't like me. I want to make it clear, I like your mod. I'll continue to use it despite my complaints. Whatever you're trying to achieve here, you've done a good job. 

The solution to my issue is clear at this point, I need to make the changes myself. What I want to see in this mod is clearly a personal preference that you don't agree with, and it would be unreasonable that I expect you accommodate me.

**Comment by Maiazye** [comment]
> @Maiazye Also, if you have any other questions, feel free to ask, I will be happy to clarify.
> 
> I have a bunch of stuff in the wiki on how temperature works. This reminds me I need to add a section for water usage as well: https://github.com/wendall911/Homeostatic/wiki/Temperature-Calculations

I would like to see a section on water usage. Some of your replies here have taught me things about the mod I was not aware of/hadn't noticed.
