### ISSUE TITLE
enhancement suggestion (1.18.2)

### ISSUE THREAD

**Issue by MoonMoonShark** [wendall911/Homeostatic#8]
maybe this already exists and i don't know how to do it, but it would be nice to be able to remove the insulation/waterproofing/radiation protection from armor.

**Comment by wendall911** [comment]
I'll have to think on this a bit. It would take another recipe to remove. Can you explain the reason? It might help with figuring out what could potentially be done.

**Comment by wendall911** [comment]
I'm thinking maybe a grindstone or anvil recipe. I'll mess around and see what can be done. Could be useful.

**Comment by MoonMoonShark** [comment]
it seems that having insulation, waterproofing, AND radiation protection on all 4 pieces of armor seems to be a bit too much protection, and i seem to be freezing to death all the time at my mountain home. i thought maybe if i didn't have radiation protection on them, i might absorb more heat from the campfire, but i am wearing Silents Gear, which wasn't cheap to make, and i don't remember how to remake it. i thought maybe if i could take some of the protections off, i would be able to adjust them as needed to get the right balance.

**Comment by MoonMoonShark** [comment]
but then, i also discovered that wearing an Everlasting Abilities Fire Protection makes a huge difference. with no armor on, standing next to the campfire in my house with just Level 1 Fire Protection totem set the local temperature to 15F, but with it removed, it went up to over 100F. there are a lot of factors to tweak here! (that's not a complaint, simply a statement of learning curve)

**Comment by wendall911** [comment]
@MoonMoonShark  Ok, thanks for the feedback! That's what I thought. Even though I created the mod, one of the first issues I had was adding Radiation Protection in the summer and some nether stuff, then getting to winter in my mountain base and realizing I couldn't get warm by the fire. 

I will work on this soon. Am exploring using a grindstone possibly, as I think that might make the most sense. I'll keep you updated. I just added a book as well with some more tips on gameplay mechanics, so grab the latest version if you want more information.

**Comment by wendall911** [comment]
I added this to the latest release. The Grindstone was a dead end, as it isn't very easy to provide custom recipes without a bunch of mixins, so I went with just standard custom recipes for removal. Since I don't want to further pollute JEI/REI recipes, I just have the recipes show in the book under the relevant gameplay section as shown below:

![2022-11-11_10 15 52](https://user-images.githubusercontent.com/44465/201408325-6faf3e3a-31c6-4822-a298-8e86a48a598b.png)
![2022-11-11_10 15 56](https://user-images.githubusercontent.com/44465/201408340-87099d52-8acb-47e9-a75f-0316b2f18941.png)
![2022-11-11_10 16 00](https://user-images.githubusercontent.com/44465/201408349-a7c28c65-b6fa-469d-a46d-dd619b849f15.png)

**Comment by MoonMoonShark** [comment]
WOO! awesome! thank you!
